/*
-----------------------------------------------------------------
          The Japanese TTS System "Open JTalk"
          developed by HTS Working Group
          http://open-jtalk.sourceforge.net/
-----------------------------------------------------------------

 Copyright (c) 2008-2014  Nagoya Institute of Technology
                          Department of Computer Science

All rights reserved.

Redistribution and use in source and binary forms, with or
without modification, are permitted provided that the following
conditions are met:

- Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
- Redistributions in binary form must reproduce the above
  copyright notice, this list of conditions and the following
  disclaimer in the documentation and/or other materials provided
  with the distribution.
- Neither the name of the HTS working group nor the names of its
  contributors may be used to endorse or promote products derived
  from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
*/
#include <vector>
#include <string>
#include <tuple>
#include <map>
std::vector<std::string> MoraKana = {
    "ァ",
    "ア",
    "ィ",
    "イ",
    "イェ",
    "ゥ",
    "ウ",
    "ウィ",
    "ウゥ",
    "ウェ",
    "ウォ",
    "ェ",
    "エ",
    "ォ",
    "オ",
    "カ",
    "ガ",
    "キ",
    "キィ",
    "キェ",
    "キャ",
    "キュ",
    "キョ",
    "ギ",
    "ギィ",
    "ギェ",
    "ギャ",
    "ギュ",
    "ギョ",
    "ク",
    "クァ",
    "クィ",
    "クゥ",
    "クェ",
    "クォ",
    "クヮ",
    "グ",
    "グァ",
    "グィ",
    "グゥ",
    "グェ",
    "グォ",
    "グヮ",
    "ケ",
    "ゲ",
    "コ",
    "ゴ",
    "サ",
    "ザ",
    "シ",
    "シェ",
    "シャ",
    "シュ",
    "ショ",
    "ジ",
    "ジェ",
    "ジャ",
    "ジュ",
    "ジョ",
    "ス",
    "スィ",
    "ズ",
    "ズィ",
    "セ",
    "ゼ",
    "ソ",
    "ゾ",
    "タ",
    "ダ",
    "チ",
    "チェ",
    "チャ",
    "チュ",
    "チョ",
    "ヂ",
    "ヂェ",
    "ヂャ",
    "ヂュ",
    "ヂョ",
    "ッ",
    "ツ",
    "ツァ",
    "ツィ",
    "ツェ",
    "ツォ",
    "ヅ",
    "テ",
    "ティ",
    "テェ",
    "テャ",
    "テュ",
    "テョ",
    "デ",
    "ディ",
    "デェ",
    "デャ",
    "デュ",
    "デョ",
    "ト",
    "トゥ",
    "ド",
    "ドゥ",
    "ナ",
    "ニ",
    "ニィ",
    "ニェ",
    "ニャ",
    "ニュ",
    "ニョ",
    "ヌ",
    "ネ",
    "ノ",
    "ハ",
    "バ",
    "パ",
    "ヒ",
    "ヒィ",
    "ヒェ",
    "ヒャ",
    "ヒュ",
    "ヒョ",
    "ビ",
    "ビィ",
    "ビェ",
    "ビャ",
    "ビュ",
    "ビョ",
    "ピ",
    "ピィ",
    "ピェ",
    "ピャ",
    "ピュ",
    "ピョ",
    "フ",
    "ファ",
    "フィ",
    "フェ",
    "フォ",
    "ブ",
    "プ",
    "ヘ",
    "ベ",
    "ペ",
    "ホ",
    "ボ",
    "ポ",
    "マ",
    "ミ",
    "ミィ",
    "ミェ",
    "ミャ",
    "ミュ",
    "ミョ",
    "ム",
    "メ",
    "モ",
    "ャ",
    "ヤ",
    "ュ",
    "ユ",
    "ョ",
    "ヨ",
    "ラ",
    "リ",
    "リィ",
    "リェ",
    "リャ",
    "リュ",
    "リョ",
    "ル",
    "レ",
    "ロ",
    "ヮ",
    "ワ",
    "ヰ",
    "ヱ",
    "ヲ",
    "ン",
    "ヴ",
    "ヴァ",
    "ヴィ",
    "ヴェ",
    "ヴォ",
    "ヴャ",
    "ヴュ",
    "ヴョ",
    "ヶ",
};
std::vector<std::tuple<std::string, std::string, std::string>> mora_list_minimum = {

    {"ヴォ", "v", "o"},
    {"ヴェ", "v", "e"},
    {"ヴィ", "v", "i"},
    {"ヴァ", "v", "a"},
    {"ヴ", "v", "u"},
    {"ン", "", "N"},
    {"ワ", "w", "a"},
    {"ロ", "r", "o"},
    {"レ", "r", "e"},
    {"ル", "r", "u"},
    {"リョ", "ry", "o"},
    {"リュ", "ry", "u"},
    {"リャ", "ry", "a"},
    {"リェ", "ry", "e"},
    {"リィ", "ry", "i"},
    {"リ", "r", "i"},
    {"ラ", "r", "a"},
    {"ヨ", "y", "o"},
    {"ユ", "y", "u"},
    {"ヤ", "y", "a"},
    {"モ", "m", "o"},
    {"メ", "m", "e"},
    {"ム", "m", "u"},
    {"ミョ", "my", "o"},
    {"ミュ", "my", "u"},
    {"ミャ", "my", "a"},
    {"ミェ", "my", "e"},
    {"ミィ", "my", "i"},
    {"ミ", "m", "i"},
    {"マ", "m", "a"},
    {"ポ", "p", "o"},
    {"ボ", "b", "o"},
    {"ホ", "h", "o"},
    {"ペ", "p", "e"},
    {"ベ", "b", "e"},
    {"ヘ", "h", "e"},
    {"プ", "p", "u"},
    {"ブ", "b", "u"},
    {"フォ", "f", "o"},
    {"フェ", "f", "e"},
    {"フィ", "f", "i"},
    {"ファ", "f", "a"},
    {"フ", "f", "u"},
    {"ピョ", "py", "o"},
    {"ピュ", "py", "u"},
    {"ピャ", "py", "a"},
    {"ピェ", "py", "e"},
    {"ピィ", "py", "i"},
    {"ピ", "p", "i"},
    {"ビョ", "by", "o"},
    {"ビュ", "by", "u"},
    {"ビャ", "by", "a"},
    {"ビェ", "by", "e"},
    {"ビィ", "by", "i"},
    {"ビ", "b", "i"},
    {"ヒョ", "hy", "o"},
    {"ヒュ", "hy", "u"},
    {"ヒャ", "hy", "a"},
    {"ヒェ", "hy", "e"},
    {"ヒィ", "hy", "i"},
    {"ヒ", "h", "i"},
    {"パ", "p", "a"},
    {"バ", "b", "a"},
    {"ハ", "h", "a"},
    {"ノ", "n", "o"},
    {"ネ", "n", "e"},
    {"ヌ", "n", "u"},
    {"ニョ", "ny", "o"},
    {"ニュ", "ny", "u"},
    {"ニャ", "ny", "a"},
    {"ニェ", "ny", "e"},
    {"ニィ", "ny", "i"},
    {"ニ", "n", "i"},
    {"ナ", "n", "a"},
    {"ドゥ", "d", "u"},
    {"ド", "d", "o"},
    {"トゥ", "t", "u"},
    {"ト", "t", "o"},
    {"デョ", "dy", "o"},
    {"デュ", "dy", "u"},
    {"デャ", "dy", "a"},
    {"デェ", "dy", "e"},
    {"ディ", "d", "i"},
    {"デ", "d", "e"},
    {"テョ", "ty", "o"},
    {"テュ", "ty", "u"},
    {"テャ", "ty", "a"},
    {"テェ", "ty", "e"},
    {"ティ", "t", "i"},
    {"テ", "t", "e"},
    {"ツォ", "ts", "o"},
    {"ツェ", "ts", "e"},
    {"ツィ", "ts", "i"},
    {"ツァ", "ts", "a"},
    {"ツ", "ts", "u"},
    {"ッ", "", "cl"},
    {"チョ", "ch", "o"},
    {"チュ", "ch", "u"},
    {"チャ", "ch", "a"},
    {"チェ", "ch", "e"},
    {"チ", "ch", "i"},
    {"ダ", "d", "a"},
    {"タ", "t", "a"},
    {"ゾ", "z", "o"},
    {"ソ", "s", "o"},
    {"ゼ", "z", "e"},
    {"セ", "s", "e"},
    {"ズィ", "z", "i"},
    {"ズ", "z", "u"},
    {"スィ", "s", "i"},
    {"ス", "s", "u"},
    {"ジョ", "j", "o"},
    {"ジュ", "j", "u"},
    {"ジャ", "j", "a"},
    {"ジェ", "j", "e"},
    {"ジ", "j", "i"},
    {"ショ", "sh", "o"},
    {"シュ", "sh", "u"},
    {"シャ", "sh", "a"},
    {"シェ", "sh", "e"},
    {"シ", "sh", "i"},
    {"ザ", "z", "a"},
    {"サ", "s", "a"},
    {"ゴ", "g", "o"},
    {"コ", "k", "o"},
    {"ゲ", "g", "e"},
    {"ケ", "k", "e"},
    {"グヮ", "gw", "a"},
    {"グォ", "gw", "o"},
    {"グェ", "gw", "e"},
    {"グゥ", "gw", "u"},
    {"グィ", "gw", "i"},
    {"グ", "g", "u"},
    {"クヮ", "kw", "a"},
    {"クォ", "kw", "o"},
    {"クェ", "kw", "e"},
    {"クゥ", "kw", "u"},
    {"クィ", "kw", "i"},
    {"ク", "k", "u"},
    {"ギョ", "gy", "o"},
    {"ギュ", "gy", "u"},
    {"ギャ", "gy", "a"},
    {"ギェ", "gy", "e"},
    {"ギィ", "gy", "i"},
    {"ギ", "g", "i"},
    {"キョ", "ky", "o"},
    {"キュ", "ky", "u"},
    {"キャ", "ky", "a"},
    {"キェ", "ky", "e"},
    {"キィ", "ky", "i"},
    {"キ", "k", "i"},
    {"ガ", "g", "a"},
    {"カ", "k", "a"},
    {"オ", "", "o"},
    {"エ", "", "e"},
    {"ウォ", "w", "o"},
    {"ウェ", "w", "e"},
    {"ウゥ", "w", "u"},
    {"ウィ", "w", "i"},
    {"ウ", "", "u"},
    {"イェ", "y", "e"},
    {"イ", "", "i"},
    {"ア", "", "a"},
};
std::vector<std::tuple<std::string, std::string, std::string>> mora_list_additional = {
    {"ヴョ", "by", "o"},
    {"ヴュ", "by", "u"},
    {"ヴャ", "by", "a"},
    {"ヲ", "", "o"},
    {"ヱ", "", "e"},
    {"ヰ", "", "i"},
    {"ヮ", "w", "a"},
    {"ョ", "y", "o"},
    {"ュ", "y", "u"},
    {"ヅ", "z", "u"},
    {"ヂョ", "j", "o"},
    {"ヂュ", "j", "u"},
    {"ヂャ", "j", "a"},
    {"ヂェ", "j", "e"},
    {"ヂ", "j", "i"},
    {"グァ", "gw", "a"},
    {"クァ", "kw", "a"},
    {"ヶ", "k", "e"},
    {"ャ", "y", "a"},
    {"ォ", "", "o"},
    {"ェ", "", "e"},
    {"ゥ", "", "u"},
    {"ィ", "", "i"},
    {"ァ", "", "a"},
};
std::map<std::string, std::string> mora_phonemes_to_mora_kana = std::map<std::string, std::string>();
std::map<std::string, std::pair<std::string, std::string>> mora_kana_to_mora_phonemes = std::map<std::string, std::pair<std::string, std::string>>();

void init_mora_mapping()
{
  if (mora_phonemes_to_mora_kana.size() == 0)
  {
    for (auto &&[kana, consonant, vowel] : mora_list_minimum)
    {
      mora_phonemes_to_mora_kana.emplace(consonant + vowel, kana);
    }
  }
  if (mora_kana_to_mora_phonemes.size() == 0)
  {
    for (auto &&[kana, consonant, vowel] : mora_list_minimum)
    {
      mora_kana_to_mora_phonemes.emplace(kana, std::pair(consonant, vowel));
    }
  }
}
